# Generated by Django 2.1 on 2021-06-27 00:05

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasereference',
            name='course',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='created',
        ),
        migrations.RemoveField(
            model_name='course',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='course',
            name='trial',
        ),
        migrations.RemoveField(
            model_name='course',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='score',
            name='send_count',
        ),
        migrations.AddField(
            model_name='assignment',
            name='show_question',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments1', to='voting.Course'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments1', to='voting.Course'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies1', to='voting.Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentors1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('text', 'video', 'image', 'file')}, on_delete=django.db.models.deletion.CASCADE, related_name='content_type1', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='content',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents1', to='voting.Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules1', to='voting.Department'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_access',
            field=models.CharField(blank=True, choices=[('Accountancy', 'Accountancy'), ('Agricultural Technology', 'Agricultural Technology'), ('Agricultural and Bio-Environmental Engineering', 'Agricultural and Bio-Environmental Engineering'), ('Architecture', 'Architecture'), ('Art Education', 'Art Education'), ('Banking and Finance', 'Banking and Finance'), ('Biological Science', 'Biological Science'), ('Building Technology', 'Building Technology'), ('Business Administration', 'Business Administration'), ('Business Education', 'Business Education'), ('Chemical Engineering', 'Chemical Engineering'), ('Chemical Science', 'Chemical Science'), ('Civil Engineering', 'Civil Engineering'), ('Computer Engineering', 'Computer Engineering'), ('Computer Technology', 'Computer Technology'), ('Educational Foundation', 'Educational Foundation'), ('Electrical Electronics Engineering', 'Electrical Electronics Engineering'), ('Estate Management', 'Estate Management'), ('Fashion Design', 'Fashion Design'), ('Fine Art', 'Fine Art'), ('Food Technology', 'Food Technology'), ('Graphics Design', 'Graphics Design'), ('Hospitality Management Technology', 'Hospitality Management Technology'), ('Industrial Design', 'Industrial Design'), ('Industrial Maintenance Engineering', 'Industrial Maintenance Engineering'), ('Languages', 'Languages'), ('Leisure and Tourism', 'Leisure and Tourism'), ('Marine Engineering', 'Marine Engineering'), ('Marketing', 'Marketing'), ('Mass Communication', 'Mass Communication'), ('Mathematics', 'Mathematics'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Mechatronics Engineering', 'Mechatronics Engineering'), ('Metallurgical Engineering', 'Metallurgical Engineering'), ('Mineral and Petroleum Resources Engineering', 'Mineral and Petroleum Resources Engineering'), ('Nutrition and Dietetics', 'Nutrition and Dietetics'), ('Office Technology Management', 'Office Technology Management'), ('Physical Science', 'Physical Science'), ('Polymer and Textile', 'Polymer and Textile'), ('Printing Technology', 'Printing Technology'), ('Public Administration', 'Public Administration'), ('Quantity Survey', 'Quantity Survey'), ('Science Laboratory Technology', 'Science Laboratory Technology'), ('Social Science', 'Social Science'), ('Statistics', 'Statistics'), ('Survey and Geoinfomatics', 'Survey and Geoinfomatics'), ('Technical Education', 'Technical Education'), ('Urban and Regional Planning', 'Urban and Regional Planning'), ('Vocational Education', 'Vocational Education'), ('Welding and Fabrication Engineering', 'Welding and Fabrication Engineering')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_created1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='department',
            name='level',
            field=models.CharField(blank=True, choices=[('ND1', 'ND1'), ('ND2', 'ND2'), ('ND3', 'ND3'), ('HND1', 'HND1'), ('HND2', 'HND2'), ('HND3', 'HND3'), ('100L', '100L'), ('200L', '200L'), ('300L', '300L'), ('400L', '400L')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='overview',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='department',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses1', to='voting.School'),
        ),
        migrations.AlterField(
            model_name='department',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='courses_joined1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='departmentalaccess',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Department_courses1', to='voting.Department'),
        ),
        migrations.AlterField(
            model_name='departmentalaccesslevel',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Department1_level1', to='voting.Department'),
        ),
        migrations.AlterField(
            model_name='score',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_assignments1', to='voting.Assignment'),
        ),
        migrations.AlterField(
            model_name='score',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_department1', to='voting.Department'),
        ),
        migrations.AlterField(
            model_name='score',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_course1', to='voting.Course'),
        ),
        migrations.AlterField(
            model_name='score',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignment1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PurchaseReference',
        ),
    ]
