# Generated by Django 2.1 on 2021-07-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_auto_20210703_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='general',
            field=models.BooleanField(default=False),
        ),
    ]
