# Generated by Django 2.1 on 2020-12-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stores',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='duration',
            field=models.PositiveIntegerField(blank=True, choices=[('', '---------'), (14, '2 Weeks'), (28, '3 Weeks'), (31, '1 Month'), (366, '1 Year')], null=True),
        ),
        migrations.AlterField(
            model_name='shops',
            name='duration',
            field=models.PositiveIntegerField(blank=True, choices=[('', '---------'), (7, '1 Week'), (186, '6 Months'), (366, '1 Year')], null=True),
        ),
        migrations.AlterField(
            model_name='stores',
            name='duration',
            field=models.PositiveIntegerField(blank=True, choices=[('', '---------'), (7, '1 Week'), (186, '6 Months'), (366, '1 Year')], null=True),
        ),
    ]
