# Generated by Django 2.1 on 2020-12-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_auto_20201205_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
