# Generated by Django 2.1 on 2021-07-31 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_auto_20210128_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='shops',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='stores',
            name='tags',
        ),
    ]
