# Generated by Django 2.1 on 2021-03-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_auto_20210303_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_access_course',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
