# Generated by Django 2.1 on 2021-03-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0006_departmentalaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='show_question',
            field=models.BooleanField(default=False),
        ),
    ]
