# Generated by Django 2.1 on 2021-03-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0007_assignment_show_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentalaccess',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
