# Generated by Django 2.1 on 2021-03-08 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0008_departmentalaccess_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentalaccess',
            name='slug',
        ),
    ]
