# Generated by Django 2.1 on 2021-08-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0011_auto_20210311_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='general',
            field=models.BooleanField(default=False),
        ),
    ]
