# Generated by Django 2.1 on 2020-04-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfiniteScroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.PositiveIntegerField(default=0)),
                ('end', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
