# Generated by Django 2.1 on 2020-05-23 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0002_infinitescroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='amount',
            field=models.PositiveIntegerField(default=''),
        ),
    ]
