# Generated by Django 2.1 on 2020-06-02 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0005_auto_20200602_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stores',
            options={'ordering': ['-id']},
        ),
    ]
