# Generated by Django 2.1 on 2020-06-02 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0007_auto_20200602_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stores',
            old_name='image',
            new_name='logo',
        ),
    ]
