# Generated by Django 2.1 on 2020-07-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0009_stores_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='amount',
            field=models.PositiveIntegerField(default=''),
        ),
    ]
