# Generated by Django 2.1 on 2020-08-20 13:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0015_auto_20200818_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertimages',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertimages',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='advertimages',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertimages',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertimages',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='advertimages',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='advertimages',
            name='duration',
            field=models.PositiveIntegerField(blank=True, choices=[('', '---------'), (7, '1 Week'), (14, '2 Weeks'), (28, '3 Weeks'), (31, '1 Month'), (366, '1 Year')], null=True),
        ),
    ]
