# Generated by Django 2.1 on 2020-10-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0019_auto_20201015_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='bodysnippet',
        ),
        migrations.AddField(
            model_name='post',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='restrict_comment',
            field=models.BooleanField(default=False),
        ),
    ]
