# Generated by Django 2.1 on 2020-10-15 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0020_auto_20201015_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertimages',
            name='bodysnippet',
        ),
        migrations.AddField(
            model_name='advertimages',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advertimages',
            name='pic2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='advertimages',
            name='pic3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='advertimages',
            name='pic4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='advertimages',
            name='restrict_comment',
            field=models.BooleanField(default=False),
        ),
    ]
