# Generated by Django 2.1 on 2020-10-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0021_auto_20201015_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='post',
            name='restrict_comment',
        ),
        migrations.AddField(
            model_name='post',
            name='bodysnippet',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
