# Generated by Django 2.1 on 2020-10-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0023_auto_20201026_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='matric_number',
            field=models.CharField(default='0', max_length=15),
        ),
    ]
