# Generated by Django 2.1 on 2021-01-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0029_face'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertimages',
            options={'ordering': ['-id'], 'verbose_name': 'AdvertImage', 'verbose_name_plural': 'AdvertImages'},
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-id'], 'verbose_name': 'article', 'verbose_name_plural': 'articles'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='matric_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='/media/media/yctmarketbannersmall.jpg', upload_to='images/'),
        ),
    ]
