# Generated by Django 2.1 on 2021-01-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0030_auto_20210103_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='department',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='prefix',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.'), ('Engr.', 'Engr.'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Miss.', 'Miss.')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='matric_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images/'),
        ),
    ]
