# Generated by Django 2.1 on 2021-01-29 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0031_auto_20210128_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='department',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
