# Generated by Django 2.1 on 2021-02-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0033_auto_20210202_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
