# Generated by Django 2.1 on 2021-02-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0034_auto_20210202_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='level',
            field=models.CharField(blank=True, choices=[('', '---------'), ('N1', 'ND1'), ('N2', 'ND2'), ('N3', 'ND3'), ('H1', 'HND1'), ('H2', 'HND2'), ('H3', 'HND3'), ('100', '100L'), ('200', '200L'), ('300', '300L'), ('400', '400L')], max_length=10, null=True),
        ),
    ]
