# Generated by Django 2.1 on 2021-02-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0035_phonenumber_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='dob',
            field=models.DateField(blank=True, default='2020-01-01', null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='department',
            field=models.CharField(blank=True, choices=[('', '---------'), ('N1', 'ND1'), ('N2', 'ND2'), ('N3', 'ND3'), ('H1', 'HND1'), ('H2', 'HND2'), ('H3', 'HND3'), ('100', '100L'), ('200', '200L'), ('300', '300L'), ('400', '400L')], max_length=300, null=True),
        ),
    ]
