# Generated by Django 2.1 on 2021-07-31 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0038_auto_20210223_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
