# Generated by Django 2.1 on 2021-08-06 01:05

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0041_departmentalaccesslevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertimages',
            name='level',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ND1', 'ND1'), ('ND2', 'ND2'), ('ND3', 'ND3'), ('HND1', 'HND1'), ('HND2', 'HND2'), ('HND3', 'HND3'), ('100L', '100L'), ('200L', '200L'), ('300L', '300L'), ('400L', '400L')], max_length=46, null=True),
        ),
    ]
