# Generated by Django 2.1 on 2021-08-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0044_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertimages',
            name='department',
        ),
        migrations.AddField(
            model_name='advertimages',
            name='department',
            field=models.ManyToManyField(related_name='user_department', to='ent.Departments'),
        ),
    ]
