# Generated by Django 2.1 on 2021-08-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0045_auto_20210806_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertimages',
            name='department',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_department', to='ent.Departments'),
        ),
    ]
