# Generated by Django 2.1 on 2021-08-17 04:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0048_auto_20210814_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationReference',
            fields=[
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=150)),
                ('phoneNumber', models.CharField(max_length=14)),
            ],
        ),
    ]
